services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: dusk
      POSTGRES_PASSWORD: dusk
      POSTGRES_DB: dusk
    ports:
      - '5430:5432'
