
GET http://localhost:3000/


###
GET http://localhost:3000/seed

###
DELETE  http://localhost:3000/deleteSeed


###
GET http://localhost:3000/categoria
###

GET http://localhost:3000/ideas


###
POST http://localhost:3000/ideas
Content-Type : application/json

{
  "titulo"    :    "Aprende Angular",
  "descripcion"  : "es un Framework de JavaScript",
  "categoriaId"  : "03cc06f4-1c69-458d-a7ef-3065b96ecb2a"
  
}


###
POST http://localhost:3000/ideas/ad2be3a7-c49b-4277-aa45-eb4b5e004b61